name: External Trigger Workflow

on:
  repository_dispatch:
    types: [deploy-request]

jobs:
  external-event:
    runs-on: ubuntu-latest

    steps:
        - name: Print environment
          run: echo "Deploying to environment: ${{ github.event.client_payload.environment || 'not provided' }}"
