name: hello
on:
  push:
    branches:
      - main
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to the users
        run: echo "hello dosto"
      - name: say hello to the username
        run: echo "hello $USER"
show-version:
  runs-on: ubuntu-latest
  steps:
    - name: this will show version of software
    - run: docker --version && python --version
